/**
 * 16px-wide base64 WebP placeholder painted behind /profile.webp while it
 * loads. Generated by scripts/portrait.mjs — do not edit by hand.
 */
export const portraitPlaceholder =
  "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAABwBACdASoQABIAPrVInkmnJCKhMAgA4BaJZQC1CHAgpBf2oIhzY9ylwjkBwAD+6+PHqmoMyOnizIrMft460mIleXdGdIUZW0rLr3JsXATXbGk/WJ//MzvJgReH4/7BtYsJIkgevLAf7BtUcw2aoAAA";
