// Converts public/profile.png to public/profile.webp (900px wide, quality 82,
// asserted <= 150 KB) and writes the 16px-wide base64 placeholder to
// lib/portrait.ts. Run with: node scripts/portrait.mjs
import { createRequire } from "node:module";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "public", "profile.png");
const out = join(root, "public", "profile.webp");
const placeholderFile = join(root, "lib", "portrait.ts");
const MAX_BYTES = 150 * 1024;

// sharp is not a direct dependency, but pnpm keeps next's optional copy in
// the store; resolve it from there before giving up.
function loadSharp() {
  const require = createRequire(join(root, "package.json"));
  try {
    return require("sharp");
  } catch {
    const store = join(root, "node_modules", ".pnpm");
    if (existsSync(store)) {
      const hit = readdirSync(store).find((d) => d.startsWith("sharp@"));
      if (hit) return require(join(store, hit, "node_modules", "sharp"));
    }
    return null;
  }
}

function writePlaceholderModule(dataUri) {
  const module = `/**
 * 16px-wide base64 WebP placeholder painted behind /profile.webp while it
 * loads. Generated by scripts/portrait.mjs — do not edit by hand.
 */
export const portraitPlaceholder =
  "${dataUri}";
`;
  writeFileSync(placeholderFile, module);
}

const sharpFactory = loadSharp();

if (sharpFactory) {
  const sharp = sharpFactory.default ?? sharpFactory;
  const full = await sharp(src).resize({ width: 900 }).webp({ quality: 82 }).toBuffer();
  if (full.byteLength > MAX_BYTES) {
    throw new Error(`profile.webp is ${full.byteLength} bytes, over the ${MAX_BYTES} budget`);
  }
  writeFileSync(out, full);

  const tiny = await sharp(src).resize({ width: 16 }).webp({ quality: 60 }).toBuffer();
  const dataUri = `data:image/webp;base64,${tiny.toString("base64")}`;
  writePlaceholderModule(dataUri);

  console.log(`profile.webp: ${(full.byteLength / 1024).toFixed(1)} KB (budget 150 KB)`);
  console.log(`placeholder (${tiny.byteLength} bytes) written to lib/portrait.ts:`);
  console.log(dataUri);
} else {
  // Fallback: no sharp and nothing gets installed. Resize with sips, convert
  // with cwebp when present; otherwise keep the resized PNG and say so.
  console.warn("sharp not resolvable; falling back to sips");
  const resized = join(root, "public", "profile-900.png");
  execFileSync("sips", ["--resampleWidth", "900", src, "--out", resized]);
  let hasCwebp = true;
  try {
    execFileSync("cwebp", ["-q", "82", resized, "-o", out]);
  } catch {
    hasCwebp = false;
    console.warn("cwebp not found; public/profile-900.png kept as a resized PNG only");
  }
  if (hasCwebp) {
    const size = statSync(out).size;
    if (size > MAX_BYTES) throw new Error(`profile.webp is ${size} bytes, over the ${MAX_BYTES} budget`);
    const tinyPng = join(root, "public", "profile-16.png");
    execFileSync("sips", ["--resampleWidth", "16", src, "--out", tinyPng]);
    const tinyWebp = join(root, "public", "profile-16.webp");
    execFileSync("cwebp", ["-q", "60", tinyPng, "-o", tinyWebp]);
    const dataUri = `data:image/webp;base64,${readFileSync(tinyWebp).toString("base64")}`;
    writePlaceholderModule(dataUri);
    console.log(dataUri);
  }
}
